"""Build global WenKai webfonts from official Regular and Medium TTF files.

Usage: python build_reading_fonts.py regular.ttf medium.ttf
Requires fonttools and brotli. Includes common Chinese and all current site
characters in the core; remaining glyphs load through unicode-range shards.
"""

import argparse
import hashlib
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FAMILY = "DooJank Reading Kai"


def ranges(points):
    groups = []
    for point in sorted(points):
        if groups and point == groups[-1][1] + 1:
            groups[-1][1] = point
        else:
            groups.append([point, point])
    return ",".join(f"U+{start:X}" + (f"-{end:X}" if start != end else "") for start, end in groups)


def core_characters():
    points = set(range(0x20, 0x100))
    for first in range(0xA1, 0xF8):
        for second in range(0xA1, 0xFF):
            try:
                points.update(map(ord, bytes([first, second]).decode("gb2312")))
            except UnicodeDecodeError:
                pass
    for folder in ["articles", "en", "zh", "classics", "_data", "_includes", "_layouts"]:
        for path in (ROOT / folder).rglob("*"):
            if path.is_file() and path.suffix in {".md", ".json", ".yml", ".html", ".txt"}:
                if path.name in {"production.md", "cover-review.md", "x.html", "x.md", "wechat.html", "wechat.md"}:
                    continue
                points.update(map(ord, path.read_text(encoding="utf-8", errors="ignore")))
    return points


def build(regular, medium):
    output = ROOT / "assets/fonts/reading-kai"
    output.mkdir(parents=True, exist_ok=True)
    core = core_characters()
    css = ["/* Generated by scripts/build_reading_fonts.py. OFL license: ../OFL-LXGW-WenKai.txt */"]
    for source, label, weight in [(regular, "regular", "100 499"), (medium, "medium", "500 900")]:
        with TTFont(source) as original:
            supported = set(original.getBestCmap())
        common = core & supported
        remaining = sorted(supported - common)
        groups = [common] + [set(remaining[i:i + 2048]) for i in range(0, len(remaining), 2048)]
        for index, points in enumerate(groups):
            with TTFont(source) as font:
                options = subset.Options()
                options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
                options.name_legacy = True
                options.name_languages = ["*"]
                subsetter = subset.Subsetter(options=options)
                subsetter.populate(unicodes=points)
                subsetter.subset(font)
                for record in font["name"].names:
                    if record.nameID in {1, 3, 4, 6, 16}:
                        value = FAMILY if record.nameID in {1, 16} else f"DooJankReadingKai-{label}"
                        record.string = value.encode(record.getEncoding())
                font.flavor = "woff2"
                data = BytesIO()
                font.save(data)
            payload = data.getvalue()
            version = hashlib.sha256(payload).hexdigest()[:10]
            name = f"{label}-{'core' if index == 0 else index}-{version}.woff2"
            (output / name).write_bytes(payload)
            css.append(f'@font-face{{font-family:"{FAMILY}";src:url("./{name}") format("woff2");font-style:normal;font-weight:{weight};font-display:swap;unicode-range:{ranges(points)};}}')
            print(label, index, len(points), len(payload), name, flush=True)
    (output / "reading-kai.css").write_text("\n".join(css) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("regular", type=Path)
    parser.add_argument("medium", type=Path)
    args = parser.parse_args()
    build(args.regular, args.medium)
